{% set data = load_setup_py_data() %}
{% set version = data.get('version') %}
{% set release = '.'.join(version.split('.')[:2]) %}

package:
  name: q2-demux
  version: {{ version }}

source:
  path: ../..
build:
  script: python setup.py install

requirements:
  build:
    - python 3.5*
    - setuptools

  run:
    - python 3.5*
    - setuptools
    - pandas
    - numpy
    - scikit-bio
    - seaborn
    - psutil
    # `ipywidgets` included to avoid ShimWarning from
    # `seaborn` imports:
    #  https://github.com/mwaskom/seaborn/issues/874
    - ipywidgets
    - qiime2 {{ release }}.*
    - q2templates {{ release }}.*
    - q2-types {{ release }}.*

test:
  imports:
    - q2_demux
    - qiime2.plugins.demux

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
